#!/usr/bin/env node
'use strict';
// PostToolUse (Edit|Write) — a mechanical backstop for AGENTS.md's "never edit a
// generated file by hand" rule: catalog.json and the plugin manifests must be
// regenerated by hand after any skills/agents/workflows/bundles source changes,
// and this is easy to forget mid-edit.
// Plain stdout from a PostToolUse hook reaches the debug log and nothing else — not the
// transcript, not the model. `hookSpecificOutput.additionalContext` is the one field that
// puts the line in front of Claude, so the reminder is written as JSON or not at all.
const path = require('path');

let raw = '';
process.stdin.on('data', (chunk) => { raw += chunk; });
process.stdin.on('end', () => {
  let input;
  try { input = JSON.parse(raw); } catch { return; }
  const filePath = input.tool_input && input.tool_input.file_path;
  if (!filePath) return;
  const cwd = input.cwd || process.cwd();
  const rel = path.relative(cwd, filePath).split(path.sep).join('/');
  if (!/^(skills|agents|workflows|bundles)\//.test(rel)) return;
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'PostToolUse',
      additionalContext: `Source unit changed (${rel}) — run \`npm run build\` (then \`npm test\` and \`npm run check\`) before committing.`,
    },
  }));
});
