'use strict';
const fs = require('fs');
const path = require('path');
const { ROOT, FOLDERS, OWNER_FOLDERS, KINDS, KIND_DIRS, scanUnits } = require('./units');
const { checkCatalog, scanEvalGroups } = require('./checks');
const { agentMarkdown, managedBlock } = require('./render');
const { scanHooks, claudeHooksFile, copilotHooksFile } = require('./hooks');

const CATALOG_NAME = 'engineering-catalog';
const SOURCE = 'https://github.com/krukovden/engineering-catalog';
const README_START = '<!-- catalog:start -->';
const README_END = '<!-- catalog:end -->';
// This repository's own response-style rules are written once, as the Claude Code output
// style, and mirrored into the Copilot instructions — Copilot cannot read `.claude/`, and two
// hand-kept copies had already drifted. Markers, not the whole file: the memory block and
// anything else in that file is the user's.
const STYLE_SOURCE = '.claude/output-styles/terse.md';
const COPILOT_INSTRUCTIONS = '.github/copilot-instructions.md';
const STYLE_START = '<!-- engineering-catalog:style:start -->';
const STYLE_END = '<!-- engineering-catalog:style:end -->';
const OWNER = 'krukovden';
const DISPLAY_NAME = 'AI Engineering Catalog';
// Copilot-only artifacts: the agents directory the root plugin.json points at, and its hooks file.
const COPILOT_DIR = '.copilot-plugin';
const COPILOT_AGENTS_DIR = `${COPILOT_DIR}/agents`;
const FOLDER_ROLES = {
  shared: 'Used by two or more audiences — the build enforces it (§3.1).',
  developers: 'Owned by developers.', qa: 'Owned by qa.', product: 'Owned by product.', ops: 'Owned by ops.',
  'in-progress': 'Committable, never shipped.', deprecated: 'Retired, kept for the record.',
};

const json = (o) => `${JSON.stringify(o, null, 2)}\n`;
const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const entryLink = (u) => (u.kind === 'skill' ? `${u.name}/SKILL.md` : `${u.name}.md`);
const stepsText = (w) => w.steps.map((s) => Object.entries(s)[0].join(':')).join(' → ');

function folderReadme(kind, folder, units) {
  const rows = units.filter((u) => u.kind === kind && u.folder === folder);
  const lines = [`# ${KIND_DIRS[kind]}/${folder}`, '', FOLDER_ROLES[folder], ''];
  if (rows.length === 0) lines.push('_Nothing here yet._');
  else {
    lines.push('| Name | Description |', '|---|---|');
    for (const u of rows) lines.push(`| [${u.name}](${entryLink(u)}) | ${cell(u.description)} |`);
  }
  lines.push('', 'Generated by `npm run build` — do not edit.', '');
  return lines.join('\n');
}

function readmeBlock(units, bundles) {
  const skills = units.filter((u) => u.kind === 'skill');
  const agents = units.filter((u) => u.kind === 'agent');
  const workflows = units.filter((u) => u.kind === 'workflow');
  const L = [README_START, '', '### Skills', '', '| Name | Owner | Invocation | Description |', '|---|---|---|---|'];
  for (const u of skills) L.push(`| [${u.name}](${u.path}/SKILL.md) | ${u.folder} | ${u.invocation} | ${cell(u.description)} |`);
  L.push('', '### Agents', '', '| Name | Owner | Description |', '|---|---|---|');
  for (const u of agents) L.push(`| [${u.name}](${u.path}) | ${u.folder} | ${cell(u.description)} |`);
  L.push('', '### Workflows', '', '| Name | Owner | Steps | Description |', '|---|---|---|---|');
  for (const u of workflows) L.push(`| [${u.name}](${u.path}) | ${u.folder} | ${stepsText(u)} | ${cell(u.description)} |`);
  L.push('', '### Bundles', '', '| Bundle | Audience | Skills | Agents | Workflows |', '|---|---|---|---|---|');
  for (const b of bundles) L.push(`| [${b.name}](${b.path}) | ${b.audience} | ${b.skills.join(', ')} | ${b.agents.join(', ')} | ${b.workflows.join(', ')} |`);
  L.push('', README_END);
  return L.join('\n');
}

/** The output style's body, frontmatter stripped, under a heading Copilot will read. */
function styleBlock(styleFile) {
  const body = styleFile
    .replace(/^---\n[\s\S]*?\n---\n/, '')
    // The style file's own sections are top-level; here they sit under "Response style".
    .replace(/^## /gm, '### ')
    .trim();
  return [
    `<!-- generated from ${STYLE_SOURCE} by \`npm run build\` — edit that file, not this block -->`,
    '',
    '## Response style',
    '',
    body,
  ].join('\n');
}

function spliceReadme(readme, block) {
  const re = new RegExp(`${README_START}[\\s\\S]*?${README_END}`);
  if (re.test(readme)) return readme.replace(re, () => block);
  return `${readme.replace(/\s*$/, '')}\n\n${block}\n`;
}

/** Pure: every generated file for a set of PROMOTED units (plus folder READMEs for all folders). */
function generate({ units, bundles, hooks = [], allUnits = units, version, description, source = SOURCE, readme = '', styleFile = null, copilotInstructions = null, meta = {} }) {
  const promoted = units.filter((u) => u.promoted);
  const skills = promoted.filter((u) => u.kind === 'skill');
  const agents = promoted.filter((u) => u.kind === 'agent');
  const workflows = promoted.filter((u) => u.kind === 'workflow');
  const out = [];
  out.push({ path: 'catalog.json', content: json({
    name: CATALOG_NAME, description, version, source,
    skills: skills.map((s) => ({ name: s.name, description: s.description, folder: s.folder, invocation: s.invocation, platforms: s.platforms, requires: s.requires, path: s.path, version: s.version })),
    agents: agents.map((a) => ({ name: a.name, description: a.description, folder: a.folder, skills: a.skills, model: a.model, path: a.path, version: a.version })),
    workflows: workflows.map((w) => ({ name: w.name, description: w.description, folder: w.folder, steps: w.steps, path: w.path, version: w.version })),
    bundles: bundles.map((b) => ({ name: b.name, audience: b.audience, description: b.description, skills: b.skills, agents: b.agents, workflows: b.workflows })),
  }) });
  const agentPaths = agents.map((a) => `./${a.path}`);
  // Claude's manifest `skills` entries are PARENT directories holding `<name>/SKILL.md`, and with
  // `source: "."` they replace the default scan — so list the owner folders that ship a skill.
  const skillFolders = OWNER_FOLDERS.filter((f) => skills.some((s) => s.folder === f)).map((f) => `./${KIND_DIRS.skill}/${f}`);
  // What a person sees before they install: the browse row in `/plugin` and `copilot plugin
  // marketplace browse`. It is also a gate — `claude plugin validate --strict` fails a
  // marketplace with no `description` and a plugin with no `author`, and that is the same
  // check Anthropic's submission pipeline runs. package.json is the one source (CONTRIBUTING).
  // `displayName` is Claude's; Copilot's manifest schema does not list it, and an unknown key
  // there is untested — so the shared block stays to the fields both schemas name.
  const owner = meta.author || { name: OWNER };
  const listing = {
    description, version, author: owner,
    homepage: meta.homepage, repository: meta.repository, license: meta.license, keywords: meta.keywords,
  };
  out.push({ path: '.claude-plugin/marketplace.json', content: json({
    name: CATALOG_NAME, description, owner,
    plugins: [{ name: CATALOG_NAME, source: '.', displayName: DISPLAY_NAME, ...listing }],
  }) });
  out.push({ path: '.claude-plugin/plugin.json', content: json({ name: CATALOG_NAME, displayName: DISPLAY_NAME, ...listing, skills: skillFolders, agents: agentPaths, hooks: './hooks/hooks.json' }) });
  out.push({ path: 'hooks/hooks.json', content: json(claudeHooksFile(hooks)) });
  // Copilot's manifest: `skills` are the same parent folders; `agents` is ONE directory of
  // `<name>.agent.md` files (rendered below, identical to what the Copilot adapter installs);
  // `hooks` is a Copilot-format hooks file. Marketplace: `.github/plugin/marketplace.json`.
  out.push({ path: 'plugin.json', content: json({ name: CATALOG_NAME, ...listing, skills: skillFolders, agents: `./${COPILOT_AGENTS_DIR}/`, hooks: `./${COPILOT_DIR}/hooks.json` }) });
  for (const a of agents) out.push({ path: `${COPILOT_AGENTS_DIR}/${a.name}.agent.md`, content: agentMarkdown(a, { platform: 'copilot' }) });
  out.push({ path: `${COPILOT_DIR}/hooks.json`, content: json(copilotHooksFile(hooks)) });
  out.push({ path: '.github/plugin/marketplace.json', content: json({
    name: CATALOG_NAME, metadata: { description, version }, owner,
    plugins: [{ name: CATALOG_NAME, source: './', ...listing }],
  }) });
  for (const kind of KINDS) for (const folder of FOLDERS) {
    out.push({ path: `${KIND_DIRS[kind]}/${folder}/README.md`, content: folderReadme(kind, folder, allUnits) });
  }
  out.push({ path: 'README.md', content: spliceReadme(readme, readmeBlock(promoted, bundles)) });
  if (styleFile !== null && copilotInstructions !== null) {
    out.push({ path: COPILOT_INSTRUCTIONS, content: managedBlock(copilotInstructions, STYLE_START, STYLE_END, styleBlock(styleFile)) });
  }
  return out;
}

function build({ root = ROOT, check = false } = {}) {
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  const scanned = scanUnits({ root, folders: FOLDERS });
  let hooks;
  try {
    hooks = scanHooks({ root });
  } catch (e) {
    return { errors: [e.message], warnings: [], written: [], removed: [] };
  }
  const { errors, warnings } = checkCatalog({ ...scanned, evalGroups: scanEvalGroups(root) });
  const fatal = scanned.warnings.filter((w) => w.startsWith('skipped ') || w.includes('outside'));
  const allErrors = [...fatal, ...errors];
  const allWarnings = [...scanned.warnings.filter((w) => !fatal.includes(w)), ...warnings];
  if (!scanned.units.some((u) => u.promoted)) allErrors.push('no promoted units found — refusing to write an empty catalog');
  if (allErrors.length) return { errors: allErrors, warnings: allWarnings, written: [] };

  const readmePath = path.join(root, 'README.md');
  const readme = fs.existsSync(readmePath) ? fs.readFileSync(readmePath, 'utf8') : `# ${pkg.name}\n`;
  const read = (rel) => (fs.existsSync(path.join(root, rel)) ? fs.readFileSync(path.join(root, rel), 'utf8') : null);
  const styleFile = read(STYLE_SOURCE);
  const copilotInstructions = styleFile === null ? null : read(COPILOT_INSTRUCTIONS);
  const files = generate({
    units: scanned.units.filter((u) => u.promoted), allUnits: scanned.units, bundles: scanned.bundles, hooks,
    version: pkg.version, description: pkg.description, readme, styleFile, copilotInstructions,
    meta: { author: pkg.author, homepage: pkg.homepage, repository: pkg.repository, license: pkg.license, keywords: pkg.keywords },
  });
  const written = [];
  const removed = staleAgentFiles(root, files, check);
  for (const f of files) {
    const abs = path.join(root, f.path);
    const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
    if (current === f.content) continue;
    written.push(f.path);
    if (check) continue;
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, f.content);
  }
  return { errors: [], warnings: allWarnings, written, removed };
}

/** `.copilot-plugin/agents/*.agent.md` left behind by a removed or demoted agent: deleted, or reported in check mode. */
function staleAgentFiles(root, files, check) {
  const dir = path.join(root, COPILOT_AGENTS_DIR);
  if (!fs.existsSync(dir)) return [];
  const generated = new Set(files.map((f) => f.path));
  const stale = fs.readdirSync(dir).filter((n) => n.endsWith('.agent.md') && !generated.has(`${COPILOT_AGENTS_DIR}/${n}`));
  if (!check) for (const n of stale) fs.unlinkSync(path.join(dir, n));
  return stale.map((n) => `${COPILOT_AGENTS_DIR}/${n}`);
}

module.exports = {
  generate, build, CATALOG_NAME, SOURCE, README_START, README_END, OWNER_FOLDERS, COPILOT_AGENTS_DIR,
  STYLE_SOURCE, COPILOT_INSTRUCTIONS, STYLE_START, STYLE_END,
};
